<?xml version="1.0"?>
<!DOCTYPE reference_node_types [
<!ELEMENT reference_node_types (reference_node_type)*>
<!ELEMENT reference_node_type (#PCDATA | match_group)*>
<!ATTLIST reference_node_type
name CDATA #REQUIRED
icon CDATA #REQUIRED
icon_small CDATA #REQUIRED
>
<!ELEMENT match_group (#PCDATA | match)*>
<!ATTLIST match_group
appended_operator (and|or|none) "or" 
>
<!ELEMENT match (#PCDATA)>
<!ATTLIST match
term CDATA #REQUIRED
type (starts_with|ends_with|contains|length_equals|length_less|length_more|isDirectory) "ends_with" 
>
]>
<reference_node_types>
	<reference_node_type name="LabSpace" icon="labspace.png" icon_small="labspace_sm.png">
		<match_group appended_operator="and">	
			<match term="labspace.open.ac.uk" type="contains" />
		</match_group>
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="LearnSpace" icon="learnspace.png" icon_small="learnspace_sm.png">
		<match_group appended_operator="and">	
			<match term="openlearn.open.ac.uk" type="contains" />
		</match_group>
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Open2" icon="open2.png" icon_small="open2_sm.png">
		<match_group appended_operator="and">	
			<match term="open2.net" type="contains" />
		</match_group>
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
		</match_group>
	</reference_node_type>			
	<reference_node_type name="African Virtual University" icon="avu_logo_eng.png" icon_small="avu_logo_eng_sm.png">
		<match_group appended_operator="or">
			<match term="http://www.avu.org" type="starts_with" />
			<match term="www.avu.org" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="BBC Creative Archive" icon="bbc-calgcaplogo.png" icon_small="bbc-calgcaplogo_sm.png">
		<match_group appended_operator="none">	
			<match term="http://creativearchive.bbc.co.uk" type="contains" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="China Quality OpenCourseWare" icon="core-orgnav.png" icon_small="core-orgnav_sm.png">
		<match_group appended_operator="or">
			<match term="http://www.core.org.cn" type="starts_with" />
			<match term="www.core.org.cn" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Massachusetts Institute of Technology OpenCourseWare" icon="d061003-logo.png" icon_small="d061003-logo_sm.png">
		<match_group appended_operator="none">	
			<match term="http://ocw.mit.edu" type="contains" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Development Gateway Foundation" icon="development-gateway-logo.png" icon_small="development-gateway-logo_sm.png">
		<match_group appended_operator="or">
			<match term="http://www.developmentgateway.org" type="starts_with" />
			<match term="www.developmentgateway.org" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Japan OpenCourseWare Alliance" icon="JOCW_logo.png" icon_small="JOCW_logo_sm.png">
		<match_group appended_operator="or">
			<match term="http://www.jocw.jp" type="starts_with" />
			<match term="www.jocw.jp" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="University of Colorado, Physics Education Technology" icon="Phet-Flatirons-logo.png" icon_small="Phet-Flatirons-logo_sm.png">
		<match_group appended_operator="or">
			<match term="http://www.colorado.edu/physics/phet" type="starts_with" />
			<match term="www.colorado.edu/physics/phet" type="starts_with" />
			<match term="http://phet.colorado.edu" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Rice University, Connexions" icon="ricelogo.png" icon_small="ricelogo_sm.png">
		<match_group appended_operator="or">	
			<match term="http://cnx.rice.edu" type="starts_with" />
			<match term="http://cnx.org" type="starts_with" />			
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Sakai Project, Learning Management System" icon="sakai-logo.png" icon_small="sakai-logo_sm.png">
		<match_group appended_operator="or">
			<match term="http://www.sakaiproject.org" type="starts_with" />
			<match term="www.sakaiproject.org" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Foothill-De Anza Community College District, Sharing Of Free Intellectual Assets" icon="Sofia-logo.png" icon_small="Sofia-logo_sm.png">
		<match_group appended_operator="none">	
			<match term="http://sofia.fhda.edu" type="starts_with" />
		</match_group>
	</reference_node_type>		
	<reference_node_type name="Internal Reference" icon="reference-internal.png" icon_small="reference-internal_sm.png">
		<match_group appended_operator="none">
			<match term="comp://" type="starts_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Word File" icon="word.gif" icon_small="word_sm.gif">
		<match_group appended_operator="or">
			<match term=".docx" type="ends_with" />
			<match term=".doc" type="ends_with" />
			<match term=".odt" type="ends_with" />			
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Access File" icon="access.gif" icon_small="access_sm.gif">
		<match_group appended_operator="or">
			<match term=".mdbx" type="ends_with" />
			<match term=".mdb" type="ends_with" />
			<match term=".odb" type="ends_with" />			
		</match_group>
	</reference_node_type>
	<reference_node_type name="Excel File" icon="excel.gif" icon_small="excel_sm.gif">
		<match_group appended_operator="or">
			<match term=".xlsx" type="ends_with" />
			<match term=".xls" type="ends_with" />
			<match term=".ods" type="ends_with" />			
		</match_group>
	</reference_node_type>
	<reference_node_type name="PowerPoint File" icon="powerpoint.gif" icon_small="powerpoint_sm.gif">
		<match_group appended_operator="or">
			<match term=".pptx" type="ends_with" />
			<match term=".ppt" type="ends_with" />
			<match term=".odp" type="ends_with" />			
		</match_group>
	</reference_node_type>
	<reference_node_type name="RSS" icon="feed-icon.png" icon_small="feed-icon_sm.png">
		<match_group appended_operator="or">
			<match term="feed://" type="starts_with" />
		</match_group>
		<match_group appended_operator="none">
			<match term="rss.xml" type="ends_with" />
		</match_group>		
	</reference_node_type>						
	<reference_node_type name="XML File" icon="xml.gif" icon_small="xml_sm.gif">
		<match_group appended_operator="none">
			<match term=".xml" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="XSL File" icon="xsl.gif" icon_small="xsl_sm.gif">
		<match_group appended_operator="none">
			<match term=".xsl" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Text File" icon="text.gif" icon_small="text_sm.gif">
		<match_group appended_operator="none">
			<match term=".txt" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="PDF File" icon="acrobat.gif" icon_small="acrobat_sm.gif">
		<match_group appended_operator="none">
			<match term=".pdf" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Java File" icon="java.gif" icon_small="java_sm.gif">
		<match_group appended_operator="none">
			<match term=".java" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Movie Files" icon="mediaplayer.gif" icon_small="mediaplayer_sm.gif">
		<match_group appended_operator="or">
			<match term=".avi" type="ends_with" />	
			<match term=".mov" type="ends_with" />
			<match term=".wmv" type="ends_with" />
			<match term=".ram" type="ends_with" />
		</match_group>
	</reference_node_type>		
	<reference_node_type name="General Web Pages" icon="html.gif" icon_small="html_sm.gif">
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />	
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
			<match term=".html" type="ends_with" />
			<match term=".htm" type="ends_with" />
			<match term=".url" type="ends_with" />	
			<match term=".asp" type="ends_with" />
			<match term=".php" type="ends_with" />
			<match term=".jsp" type="ends_with" />
		</match_group>
	</reference_node_type>			
	<reference_node_type name="Email" icon="email.gif" icon_small="email_sm.gif">
		<match_group appended_operator="and">
			<match term="@" type="contains" />
		</match_group>
		<match_group appended_operator="none">
			<match term="100" type="length_less" />
		</match_group>		
	</reference_node_type>
	<reference_node_type name="Folder" icon="folder.png" icon_small="folder_sm.png">
		<match_group appended_operator="or">
			<match term="\\" type="starts_with" />
		</match_group>
		<match_group appended_operator="none">
			<match term="" type="isDirectory" />
		</match_group>		
	</reference_node_type>	
</reference_node_types>